### ISSUE TITLE
for old browsers

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-will-change#3]
```css
.moving-element {
  transform: translateZ(0);
}
```

https://developers.google.com/web/fundamentals/performance/rendering/stick-to-compositor-only-properties-and-manage-layer-count?hl=ru
